services:
  node-api-a:
    build: ./node-api-a
    container_name: node-api-a
    env_file:
      - ./node-api-a/.env
    ports:
      - '3001:3001'
    environment:
      - APP_NAME=node-api-a
    depends_on:
      - loki
      - jaeger
      - collector
      - fluent-bit
    volumes:
      - ./node-api-a/logs:/var/log/api-a
    networks:
      - observability

  mysql:
    image: mysql:8.0
    container_name: clicmedic_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Guy123456
      MYSQL_DATABASE: clicmedic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observability

  clicmedic_api:
    build: ./ClicMedic-api
    container_name: clicmedic_api_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clicmedic_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: java-node-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - '9090:9090'
    depends_on:
      - alertmanager
    networks:
      - observability

  alertmanager:
    image: prom/alertmanager:latest
    container_name: java-node-alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - '9093:9093'
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    container_name: java-node-loki
    ports:
      - '3100:3100'
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
    networks:
      - observability

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: java-node-fluent-bit
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./node-api-a/logs:/var/log/api-a
      - ./ClicMedic-api/logs:/var/log/clicmedic
    ports:
      - '2020:2020'
      - '2021:2021'
      - '24224:24224'
    networks:
      - observability
    depends_on:
      - loki

  jaeger:
    image: jaegertracing/all-in-one:1.33
    container_name: java-node-jaeger
    ports:
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
    networks:
      - observability

  collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - '4317:4317'
      - '4318:4318'
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    environment:
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - loki
      - jaeger
    networks:
      - observability

networks:
  observability:
    driver: bridge

volumes:
  mysql_data:
