receivers:
  jaeger:
    protocols:
      thrift_compact:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: jaeger:14250
  loki:
    endpoint: loki:3100
  prometheus:
    endpoint: '0.0.0.0:9464'

service:
  pipelines:
    traces:
      receivers: [jaeger, otlp]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [loki]
