server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

# Define pipeline stages for each API
promtail_config:
  scrape_configs:
    - job_name: api-a
      static_configs:
        - targets:
            - localhost
          labels:
            job: api-a
            __path__: /var/log/api-a/*.log
    - job_name: clicmedic
      static_configs:
        - targets:
            - localhost
          labels:
            job: clicmedic
            __path__: /var/log/clicmedic/*.log
